# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0002_custrecord_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='custrecord',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
