# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0003_auto_20161030_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'menu/')),
                ('menu_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_image', to='choose.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('menu_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_video', to='choose.Menu')),
            ],
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_order', to='choose.CustRecord'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_order', to='choose.Menu'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
